!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.otplib_hotp=t():e.otplib_hotp=t()}(this,function(){return webpackJsonp_name_([4],{1:function(e,t,n){"use strict";function o(e){return e&&e.__esModule?e:{default:e}}function u(e,t){var n=arguments.length>2&&void 0!==arguments[2]?arguments[2]:{};if(null==t)return"";var o=(0,d.default)(n),u=(0,c.default)(e,t,o),r=(0,f.default)(u.substr(u.length-1)),i=u.substr(2*r,8),a=(0,f.default)(i)&(0,f.default)("7fffffff"),s=a%Math.pow(10,o.digits);return s=(0,l.default)(s,o.digits)}Object.defineProperty(t,"__esModule",{value:!0});var r=n(21),f=o(r),i=n(6),l=o(i),a=n(14),c=o(a),s=n(5),d=o(s);t.default=u},12:function(e,t,n){"use strict";function o(e){return e&&e.__esModule?e:{default:e}}function u(e,t,n){var o=arguments.length>3&&void 0!==arguments[3]?arguments[3]:{},u=(0,l.default)(t,n,o);return!(u.length<1)&&(0,f.default)(e,u)}Object.defineProperty(t,"__esModule",{value:!0});var r=n(9),f=o(r),i=n(1),l=o(i);t.default=u},13:function(e,t,n){"use strict";function o(e){return e&&e.__esModule?e:{default:e}}function u(e){var t=(0,f.default)(e);return(0,l.default)(t,16)}Object.defineProperty(t,"__esModule",{value:!0});var r=n(22),f=o(r),i=n(6),l=o(i);t.default=u},14:function(e,t,n){"use strict";(function(e){function o(e){return e&&e.__esModule?e:{default:e}}function u(t,n,o){if("object"!==(void 0===o?"undefined":r(o))||null==o)throw new Error("[hotpDigest] argument 3 must be an object");var u=o.createHmacSecret||s.default,f=u(t,o),l=(0,a.default)(n);return i.default.createHmac(o.algorithm,f).update(new e(l,"hex")).digest("hex")}Object.defineProperty(t,"__esModule",{value:!0});var r="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},f=n(15),i=o(f),l=n(13),a=o(l),c=n(3),s=o(c);t.default=u}).call(t,n(0).Buffer)},3:function(e,t,n){"use strict";(function(e){function n(t,n){return new e(t,n.encoding)}Object.defineProperty(t,"__esModule",{value:!0}),t.default=n}).call(t,n(0).Buffer)},5:function(e,t,n){"use strict";function o(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{};return u({algorithm:"sha1",createHmacSecret:f.default,digits:6,encoding:"ascii"},e)}Object.defineProperty(t,"__esModule",{value:!0});var u=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var n=arguments[t];for(var o in n)Object.prototype.hasOwnProperty.call(n,o)&&(e[o]=n[o])}return e},r=n(3),f=function(e){return e&&e.__esModule?e:{default:e}}(r);t.default=o},51:function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.HOTP=void 0;var o=n(7),u=function(e){return e&&e.__esModule?e:{default:e}}(o);/**
 *
 * Instance of HOTP
 *
 * HMAC-based One-Time Password library
 *
 * @module hotp
 * @since 3.0.0
 * @author Gerald Yeo
 * @license MIT
 */
t.HOTP=u.default,t.default=new u.default},57:function(e,t,n){"use strict";e.exports=n(51).default},7:function(e,t,n){"use strict";function o(e){return e&&e.__esModule?e:{default:e}}function u(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});var r=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var n=arguments[t];for(var o in n)Object.prototype.hasOwnProperty.call(n,o)&&(e[o]=n[o])}return e},f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},i=function(){function e(e,t){for(var n=0;n<t.length;n++){var o=t[n];o.enumerable=o.enumerable||!1,o.configurable=!0,"value"in o&&(o.writable=!0),Object.defineProperty(e,o.key,o)}}return function(t,n,o){return n&&e(t.prototype,n),o&&e(t,o),t}}(),l=n(12),a=o(l),c=n(1),s=o(c),d=function(){function e(){u(this,e),this._options={}}return i(e,[{key:"generate",value:function(e,t){return(0,s.default)(e,t,this.options)}},{key:"check",value:function(e,t,n){return(0,a.default)(e,t,n,this.options)}},{key:"verify",value:function(e){return"object"===(void 0===e?"undefined":f(e))&&null!=e&&this.check(e.token,e.secret,e.counter)}},{key:"options",set:function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{};e&&(this._options=r({},this._options,e))},get:function(){return r({},this._options)}}]),e}();t.default=d}},[57])});